package begning;
import java.util.Scanner;
import java.util.Random;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ATM_program {
	
	public static final int Pass_LENGTH = 7;
	public static final int Account_LENGTH = 10;
	public static final int Account_Pass = 29240130;
	public static int Account_Amount = 6000;
	
	public static void main(String[]args) { try
	{	Scanner sc = new Scanner(System.in); 
		Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/Banking", "root", "MyNewPassword");//Establishing connection
		System.out.println("Connected With the database successfully");
		//Crating PreparedStatement object
	
		PreparedStatement preparedStatement=connection.prepareStatement("insert into Customers values(?,?,?,?)");
		//Setting values for Each Parameter
		System.out.println("Please enter your name");
		String name = sc.next();
		System.out.println("Please enter the address");
		String Address = sc.next();
		System.out.println("Please enter your mobile number");
		long numb = sc.nextLong();
		System.out.println("Please enter you Id number");
		long Id = sc.nextLong();
		
		preparedStatement.setString(1,name);
		         preparedStatement.setString(2,Address);
		         preparedStatement.setLong(3, numb);
		         preparedStatement.setLong(4, Id);
		         
		        
		         //Executing Query
		         preparedStatement.executeUpdate();
		         System.out.println("data inserted successfully");
		         
		} catch (SQLException e) 
				{
		System.out.println("Error while connecting to the database");
				}
	
	
	
		long n = (long)(10000000000L + new Random().nextFloat()*90000000000L);
		
		//System.out.println(n);
		System.out.println(" ");
		System.out.println("WELCOME TO XYZ BANK");
		System.out.println("________________________________\n");
		System.out.println("Are you New Customer?");
		Scanner sc = new Scanner(System.in);
		String reslt = sc.next();	
		
		
		switch(reslt)
		{
		case("yes"):
			System.out.println("Please enter your name");
			String name2 = sc.next();
			System.out.println("Below is your autogenerated Account No");
			long Accno = n;
			System.out.println(Accno);
			System.out.println("Please set a 7 digit numeric password");
			int pswd = sc.nextInt();
			
			
		case("no"):
		
		    break;
		}
		System.out.println("");
		System.out.println("Please Re-enter your 11 digit Account number to login");
		Scanner scr = new Scanner(System.in);
		String accountnum = scr.nextLine();
		isAccountisvalid(accountnum);
		String pass = scr.nextLine();
		isPasswordisvalid(pass);
		
		//System.out.println(flag);
		
		System.out.println("Do you want to see the Current Balance of your Account");
		String res = scr.next();
		if(res=="Yes" || res=="YES" || res=="yes")
		{
		System.out.println("Your current balance is: "+Account_Amount);
		}
		else
		{	
		System.out.println("Please choose your options from below: ");
		}
		System.out.println("Choose (1)Deposit and (2)Withdrawl ");
		
		int option = scr.nextInt();
		
		switch(option)
		{
		case(1):
			System.out.println("Please enter the amount to Deposit");
			int Depamt = scr.nextInt();
			Deposit(Depamt);
			break;
			
		case(2):
			System.out.println("Please enter the amount to Withdrwal");
		 	int Withamt = scr.nextInt();
		 	withdrawl(Withamt);
		    break;
		}
		
		//System.out.println("Wrong option Selected please try again!!");
		}
		
	 

	public static void withdrawl(int Withdrwl)
	{
		    if(Account_Amount<0) 
		    {
		    	System.out.println("You Have unsufficient amount in your account");
		    }
		    else 
		    {
		    int rem2 = Account_Amount - Withdrwl;
		    System.out.println("Your Updated Balance is "+rem2);
		    System.out.println("Exiting now");
		    Account_Amount = rem2;
		    }
	}
	
	public static void Deposit(int Depamtt)
	{
		int rem = Account_Amount + Depamtt;
		System.out.println("Your Updated Balance is "+rem);
	    System.out.println("Exiting now");
		Account_Amount = rem;
	}
	
	public static void isAccountisvalid(String accnum)
	{
		if(accnum.length()>Account_LENGTH)
		{
			System.out.println("\nEntered Account number is accepted");

			System.out.println("Now Please enter your ATM Password not less than 7 digits!!\n");
			
		}
		else
		{
			System.out.println("Entered Account number is less than 11 digits please try again!!\n");

		}
	}
	
	public static void isPasswordisvalid(String pass)
	{
		if(pass.length()>Pass_LENGTH)  
		{			
			if(Integer.valueOf(pass).equals(Integer.valueOf(Account_Pass))==true)
			{
			System.out.println("\nEntered Password is accepted\n");
			}
			
		else
			
		{
			System.out.println("Entered Password less than 7 digits or not correct please try again!!\n");
		}
	}
	
	}

}
